create table admin (
    id int8 generated by default as identity,
     password varchar(255),
      username varchar(255),
       primary key (id));

create table admin_role (
    admin_id int8 not null,
     admin_role varchar(255));

create table category (
    id int8 generated by default as identity,
     type_of_product varchar(255),
      primary key (id));

create table order_details (
    id int8 generated by default as identity,
      quantity int4,
       total_price float8,
        order_id int8 not null,
         product_id int8 not null,
          primary key (id));

create table orders (
    id int8 generated by default as identity,
     address varchar(255),
      city varchar(255),
       date timestamp,
        date_of_served timestamp,
         name varchar(255),
          pay_type varchar(255),
           phone varchar(255),
            session_id varchar(255),
             status varchar(255),
              primary key (id));

create table product (
    id int8 generated by default as identity,
     after_discount float8,
      discount float8,
       name varchar(255),
        photo varchar(255),
         price float8,
          product_character varchar(2000),
           product_description varchar(2000),
            register_date timestamp,
             view_count int4,
              category_id int8,
               primary key (id));

alter table if exists admin_role add constraint admin_from_role foreign key (admin_id) references admin;

alter table if exists order_details add constraint order_id foreign key (order_id) references orders;

alter table if exists order_details add constraint product_id foreign key (product_id) references product;

alter table if exists product add constraint category_id foreign key (category_id) references category;